### ISSUE TITLE
Resupply - suture medical items

### ISSUE THREAD

**Issue by 48mi** [Crowdedlight/Crows-Zeus-Additions#101]
Would it be posisble to add the sutures as an item for the resupply module?

I was going to try, but wanted to do it properly and check Ace medical settings first to see if they are reqired, this is where I failed.

**Comment by Crowdedlight** [comment]
Added in #103

**Comment by Crowdedlight** [comment]
They are just always added if ACE medical is loaded. Even if not needed with the medical settings atm.
