### ISSUE TITLE
Switch Unit module like Achillies had

### ISSUE THREAD

**Issue by Crowdedlight** [Crowdedlight/Crows-Zeus-Additions#47]
In Achilles, their is "Switch Unit" as well as "Remote Control". "Switch Unit" seems to transfer the player client temporarily into an NPC, rather than just simply remote controlling them. This is helpful for using certain vehicle scripts that cant be accessed by an npc usually, and when using old TFAR, allows you speak through the unit.

**Comment by zgthor** [comment]
Is this an issue, iirc you can now speak trough zen remote control

**Comment by Crowdedlight** [comment]
Was requested on workshop page. Seemingly only usecase is when using objects from mods where you cannot use the options if you are remote-controlling. Quite limited situations where this would be an issue and most times you would be able to just zeus teleport a player-zeus into vehicle.  
Put on ice for now.
