### ISSUE TITLE
[Bug] Unexpected behaviour when using stripExplosives with mods

### ISSUE THREAD

**Issue by Landric** [Crowdedlight/Crows-Zeus-Additions#73]
Certain mods that add grenades may produce confusing behaviour when using the stripExplosive module, depending on what base class each grenade inherits from. E.g.:
ACE Flashbangs inherit from offensive grenades - this probably will work as expected
RHS: AFRF smoke grenades inherit from offensive grenades - this will cause unexpected behaviour
ACE incendiary grenades inherit from smoke grenades - this will cause unexpected behaviour

**Comment by Crowdedlight** [comment]
Fixed in next release
