### ISSUE TITLE
Create a Zeus Module " Create IED"

### ISSUE THREAD

**Issue by Eughenos** [Crowdedlight/Crows-Zeus-Additions#77]
I am in love with the very old Achilles module [Create IED] (https://github.com/ArmaAchilles/Achilles/blob/master/%40AresModAchillesExpansion/addons/modules_f_achilles/Objects/functions/fn_ObjectsIED.sqf)).
I think you can find a way to create a **similar module** where it is possible to **transform a normal object in a IED**.
I am not a scripting pro but I can help you.

**Comment by Landric** [comment]
The successor to Achilles - [Zeus Enhanced](https://steamcommunity.com/workshop/filedetails/?id=1779063631) - already has this function: [](https://zen-mod.github.io/ZEN/#/user_guide/modules_list?id=create-ied)

**Comment by Crowdedlight** [comment]
As my mod is dependent on running Zeus Enhanced already, there is no point in recreating a module they already have. Closing this issue. If you mean a module that does something different than the Zeus Enhanced module, feel free to further elaborate on what you are suggesting.
