### ISSUE TITLE
(Feature) More Draw Build Objects

### ISSUE THREAD

**Issue by M113-ITV** [Crowdedlight/Crows-Zeus-Additions#87]
I'd like to see more objects available for use in the Draw Build Menu. Specifically, I'd like to see the option to place Grass Trench Blocks, this would save a lot of time compared to having to manually build Trenches in the Eden Editor.

**Comment by Z8MB1E** [comment]
I also think having CUP's h-barriers would be nice.

**Comment by Crowdedlight** [comment]
More options have been added in the last release as the select menu has also been redone. Also has an option now for adding custom parts by adding in the class name of the object. 

Landric have done a great job changing it and adding some new types of objects, besides the custom option.
