### ISSUE TITLE
Getting lots of Scripting command 'call' is not allowed to be remotely executed

### ISSUE THREAD

**Issue by Blueduckraider50** [Crowdedlight/Crows-Zeus-Additions#88]
As the title say, getting lots of 
"Scripting command 'call' is not allowed to be remotely executed"
when putting a Surrender Chance module on Infantry.
Because our server got most commands / functions defaulted to not-allowed to remoteExec for security reasons.
Saw in the CrowsZA/functions/fn_surrenderChance.sqf code that you have a _condition with 
[_unit, {
	missionNamespace setVariable [
		""crowsza_surrender_chance_"" + str (_this call BIS_fnc_netId),
		(toUpperANSI cameraView == ""GUNNER"") && (cursorObject == _this),
		remoteExecutedOwner
	];
}] remoteExecCall [""call"", _x];

Just wondering if it's nessessary to run a call like that constantly in a condition. Seems very inefficient & potentially causing more bandwidth usage for something that could "maybe" be done easier.
Wonder if using 
```sqf
_unit = _unit; // Unit that can surrender
_surrenderDistance; // Surrender distance
_nearbyPlayers = allPlayers - entities"HeadlessClient_F"; // All players excluding headless, can be sorted to only allow enemies, but I cba to write one
_nearbyPlayers = _nearbyPlayers select {_x distance _unit < _surrenderDistance}; // only check for units within the appropiate range.
_weaponsOnTarget = { // Gives a number of how many is looking directly at unit
   _player = _x;
   _dist = _player  distance _unit;
   _weaponDir = _player weaponDirection (currentWeapon _player);
   _units = lineIntersectsWith [eyePos _player, _weaponDir vectorMultiply( _dist + 3)];
   (_unit in _units)
} count _nearbyPlayers;
_weaponsOnTarget > 0;
```
Not tested this code, but something simular to it could work, and only runs on the zeus/server that executed the condition, instead of remoteExecing to other clients to ask them "what do you see" every X rate.

**Comment by Crowdedlight** [comment]
Thanks for the report. I agree that avoiding asking all other clients with network traffic would definitely be better. I seem to recall we had some kind of reason to distribute it out, but I can't remember on top of my head. We might just not have thought of it. 

@Landric would you be able to take a look at this? As suggested there might be a smarter way to do this that avoids remoteExec and unnecessary network traffic. I can't recall if there was a reason to not go this way, but kinda makes sense to just get the zeus machine to calculate who points at a unit locally. It's a function that isn't meant to be used against 100s of enemy AI at the same time in any case.

**Comment by Landric** [comment]
At the time, there was a reason for this (I think to detect whether a player was aiming down their sights). That said, it'd be great to reduce the network calls and improve performance, and I think that functionality isn't hugely necessary (and/or can be mimicked well-enough by checking `weaponLowered`). I'll give this a look!

**Comment by Blueduckraider50** [comment]
I had some "undercover" script written that used a "simple" direction check
```
uc_fnc_getDirection = {
	private["_direction"];
	params["_from", "_to"];
	_direction	=	(_from getRelDir _to) - 180;
	if(_direction < 0) then {
		_direction	=	_direction + 180;
	} else{
		_direction	=	_direction - 180;
	};
	_direction;
};
```

```
private["_units", "_maxFOV", "_minDistance", "_maxDistance", "_maxVisibility"];
	params["_unit",["_knows",false],["_vis",false],["_skill",true],["_light",false]];
	_maxFOV		=	150;					// FOV to be able to see you
	_maxVisibility	=	0.75;				// How much cover has effect
	_minDistance	=	1;					// Min distance AI can spot you
	_maxDistance	=	15;				// Max distance AI can spot you | Never less than double of _minDistance
	_maxGlobalDistance	=	50;			// Global distance to register AI as useful
	
	_units	=	allUnits - allPlayers;
	_units	=	_units select {alive _x};				// Is Alive
	_units	=	_units select {side _x in uc_hostiles};	// Is hostile
	//_units	=	_units select {abs([_x, _unit] call uc_fnc_getDirection) < (_maxFOV * 0.666)}; // Within views
	if(_knows) then {
		_units	=	_units select {(_x knowsAbout _unit) > 0.5};
		if(count _units > 0) exitWith {false};
	};
	_units	=	_units select {(_x distance _unit) < _maxGlobalDistance};	// Within max range
	if(_vis) then {
		_units	=	_units select {
			([objNull, "VIEW"] checkVisibility [eyePos _x, eyePos _unit]) > _maxVisibility // Not behind cover
		};
		if(count _units == 0) exitWith {true};
	}
```;
But not sure if that's of any use, haven't tested it on large scale, but on small tests it worked fine.

**Comment by Crowdedlight** [comment]
Should be fixed in latest version just released.
