### ISSUE TITLE
Paste loadouts into inventory

### ISSUE THREAD

**Issue by B0tmann** [Crowdedlight/Crows-Zeus-Additions#9]
module to convert a selected units complete loadout into an sqf command, so these items can be added to a container via init

**Comment by Crowdedlight** [comment]
So you want to copy all items the unit currently have and be able to "paste" them into the inventory space of a container?

**Comment by B0tmann** [comment]
exactly

**Comment by Crowdedlight** [comment]
Would the following feature fulfill your usecase? 
(Can come with next release)

You use the Zeus Enhanced copy loadout functionality on a unit: 
![20210412220230_1](https://user-images.githubusercontent.com/7889925/114477453-790ea980-9bfc-11eb-9c40-105f75d785b5.jpg)

You then use the extra option I have added when right-clicking and going ->inventory->Paste Loadout of an box or vehicle:
![20210412231413_1](https://user-images.githubusercontent.com/7889925/114477523-993e6880-9bfc-11eb-9bfc-64afaecaf917.jpg)

This will put all items from the loadout into the box you selected. **NOTE:** The weapons will be put in with the same attachments as the loadout, but the uniform, vest, backpack will be empty and their contents will be laying loose inside the box you selected. Also if the selected box does not have enough space, it will just skip adding items. 

As it doesn't seem possible to ensure that I put the items in the right backpack if multiple is in the box, I have opted to just put the items into the selected box. So you would still have to manually put the items into the backpack. It's the same deal with uniforms and vests as I can't seem to find methods that allow me to script and put stuff into the vest/uniforms without those being equipped on a unit. 

![20210412231435_1](https://user-images.githubusercontent.com/7889925/114478443-89c01f00-9bfe-11eb-9a3c-14b5f7d2d3f2.jpg)

**Comment by Crowdedlight** [comment]
Added wiki page: https://github.com/Crowdedlight/Crows-Zeus-Additions/wiki/Paste-Loadout-Into-Inventory

**Comment by B0tmann** [comment]
yes, thanks man

**Comment by Crowdedlight** [comment]
Sounds good. It will be in the next release sometime soon. Have a few other modules I want to take a go at before, to include them in the same release.

**Comment by Crowdedlight** [comment]
merged into develop for next release
